/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package beth.topologyTesting;

import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Carbon
 */
public class TopologyTestingPanel extends javax.swing.JPanel {
    Double[][] testScores;
    List<String> topIDs;

    /**
     * Creates new form TopologyTestingPanel
     */
    public TopologyTestingPanel() {
        initComponents();
        this.testScores = null;
        this.topIDs = null;
        this.setContents();
        
    }
    
    public void setContents() {
        TopologyDataManager manager = TopologyDataManager.getInstance();
        System.out.println("man has");
        System.out.println(manager.getScoreArray());
        if (manager.hasValues()) {
            System.out.println("manager has values");
            this.nameJList.setModel(manager.getNameListModel());
            this.auScoreJList.setModel(manager.getScoreListModel(TopologyDataManager.AU_TEST));
            this.shScoreJList.setModel(manager.getScoreListModel(TopologyDataManager.SH_TEST)); 
            this.testsDoneLabel.setEnabled(false);
            this.testsDoneLabel.setVisible(false);
        } else {
            System.out.println("manager has no values");
            this.nameJList.setModel(new DefaultListModel());
            this.auScoreJList.setModel(new DefaultListModel());
            this.shScoreJList.setModel(new DefaultListModel());
            if (!(this.testScores == null) && !(this.topIDs == null) && !manager.hasValues()) {
                manager.setScoreArray(this.testScores);
                manager.setTopologyNames(this.topIDs);
                this.setContents();
            }
        }
        
        
    }
    
    public void setTestScores(Double[][] scores) {
        this.testScores = scores;
    }
    
    public void setNames(List<String> ids) {
        this.topIDs = ids;
    }
    
    public void setMockContents() {
            ArrayList<String> mockList1 = new ArrayList<String>();
            ArrayList<String> mockList2 = new ArrayList<String>();
            ArrayList<String> mockList3 = new ArrayList<String>();
            mockList1.add("mc1");
            mockList1.add("mc2");
            mockList2.add("cal1");
            mockList2.add("val2");
            
            String[] data  = new String[2];
            data[0] = "dataa";
            data[1] = "mata";
            
            this.nameJList.setListData(data);
            this.auScoreJList.setListData(data);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        topologyLabel = new javax.swing.JLabel();
        auTestLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nameJList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        auScoreJList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        shScoreJList = new javax.swing.JList<>();
        viewTopologiesButton = new javax.swing.JButton();
        exportResultsButton = new javax.swing.JButton();
        testsDoneLabel = new javax.swing.JLabel();

        topologyLabel.setText("Topology");

        auTestLabel.setText("AU Test");

        jLabel1.setText("SH Test");

        nameJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(nameJList);

        auScoreJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(auScoreJList);

        shScoreJList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(shScoreJList);

        viewTopologiesButton.setText("View Topologies");
        viewTopologiesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewTopologiesButtonActionPerformed(evt);
            }
        });

        exportResultsButton.setText("Export Results");
        exportResultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportResultsButtonActionPerformed(evt);
            }
        });

        testsDoneLabel.setText("There seems to be nothing to find here. Your tests might still take a while");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(testsDoneLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(viewTopologiesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(topologyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(auTestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(jScrollPane2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                                    .addComponent(jScrollPane3)))
                            .addComponent(exportResultsButton, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(testsDoneLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(auTestLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(topologyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(viewTopologiesButton)
                    .addComponent(exportResultsButton))
                .addContainerGap(123, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void viewTopologiesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewTopologiesButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viewTopologiesButtonActionPerformed

    private void exportResultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportResultsButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exportResultsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<String> auScoreJList;
    private javax.swing.JLabel auTestLabel;
    private javax.swing.JButton exportResultsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> nameJList;
    private javax.swing.JList<String> shScoreJList;
    private javax.swing.JLabel testsDoneLabel;
    private javax.swing.JLabel topologyLabel;
    private javax.swing.JButton viewTopologiesButton;
    // End of variables declaration//GEN-END:variables
}
